#include "VehicleSimulation.h"
#include "tpid_class.h"
//#include <sys/ioctl.h>
//#include <termios.h>
//#include <stdbool.h>
//#include <unistd.h>
#include "Rot_Flux_Ang.hpp"
#include "ifoc.hpp"
//#include <string>
//#include <string.h>
//#include <fstream>
//#include <complex>
//#include <iomanip>
#include "variables.hpp"
#include "my_fp_2.h"
#include <math.h>
//#include <stdio.h>
#include "terminal.h"
#include "terminalcommands.h"


using namespace Maths;

#ifdef VehicleSimulation

static int gear_  = 1;

//#define Lrro (ro*Lr)//0.0021891

//total gear racio. (gear_box*final_gear*"reduction_low_ratio")
float T_G_R = (4.313/*2.33*//*1.436 1 0.789*/*4.1/*reduction:1.9*/);

float T_G_R_[] = { 4.313 /*2.33 1.436 1 0.789*/*4.1/*1.9*/, 2.33 /*1.436 1 0.789*/*4.1/*1.9*/, 1.436 /*1 0.789*/*4.1/*1.9*/, 1 /*0.789*/*4.1/*1.9*/, 0.789*4.1/*1.9*/ };
static float T_G_R_ant=T_G_R;

//road gradiente
static float gradiente=0.0;//-0.25;//0.15;

static float _fds,_fqs, ids_ant, iqs_ant;
static float fds_,fqs_;


float sum_power_out=0.001;
float sum_power_in=0.000001;
float Torq_net=0.0;
float sum_power_trac =0.0;
float sum_power_battery = 0.0;
bool DrivingCycle=true;//to set by driving cycle(DrivingCycle==true) or by throttle
int n_rtc=0;
float T_G_R_b_clutch=T_G_R_ant;//thing its not needed
//float Vf=0.0;
float Te=0.0;//torque motor
float J2=0.0;//inercia vehicle??
float w_ref_ant=0.0;
float distance_=0.0;
float velocidade=0.0;//vel. clutch
float load=0.0, load_s=0.0;
//float b, end_f;

//float pl=0.0;load
bool RoadGradienteF=true;

float torq_L=0.0;
float J=(0.071);//TODO:?? 1pv5135-4ws14: 0.071

float IDC_med=0.0;
int it_=0;

bool quit=false;

//clutch:
#define N_P 2.0
#define US 0.15
#define UD 0.24
#define FI 1.5
#define R1_ 0.074
#define R2_ 0.104
#define XTO_CNT 0.00402
#define XTO_CLS 0.00778
#define XTO_MAX 0.012
#define F_MAX 17000//5000

#define CLUTCH_TIME 0.5//0.13//0.5 sec.
int clutch_time=-1;


float TorqGenMotor=0.0;

static const float roLs = ( ro * Ls );//0.013998//ro*Ls
float fdr=0.0,fqr=0.0, Iqm=0.0, Idm=0.0, fqs=0.0, fds=0.0;


extern float ids, iqs, IDC;
float iaa_p=0.0, vaa_p=0.0, cos_phi=0.0, cos_phi_a=0.0, two_phi=0.0, desc_p=0.0, phi=0.0;//to calc cos phi. just adicional information

//////////
//float get_w_r();//TODO implement in REAL
//////////
void set_w_ref(float wreff) {w_ref=wreff;};
	float get_w_ref(){return w_ref;};
	void set_torq_L(float torque){torq_L=torque;};

	float get_torq_L(){return torq_L;};//TODO remove in real

float get_w_r(){return wr;};//TODO implement in REAL


const float ECECycle[] = { ECECYCLE };//indice 0 t0 195
const float EUDCCycle[] = { EUDCCYCLE };//indice 0 to 400
static int16_t w_refTask = 0;
static int16_t n_DrivingCycle = 0;
static uint8_t count_ECE = 4;//4 ECE cycles
   /* VehicleSimulation::*/
 bool DrivingCycleTask()
{//4 ECE + 1 EUDC
    if (n_DrivingCycle > (1.0/T) ){//TODO see if 1/T is int
        if(count_ECE==0  &&  (w_refTask < 402))
            {w_ref = EUDCCycle[w_refTask];
				}
        else{
            w_ref=ECECycle[w_refTask];
		}
		w_ref = w_ref*1000/3600*T_G_R/R;
        w_refTask++;
        if (w_refTask == 196 && count_ECE > 0 )
        {
            w_refTask = 0;
            count_ECE--;
        }
        n_DrivingCycle = 0;
    }
    n_DrivingCycle++;
        //printf("w_ref %f T_G_R %f R %f \n", FP_FROMFLT(w_ref), FP_FROMFLT(T_G_R), FP_FROMFLT(R));

   // w_ref=w_ref*1000/3600*T_G_R/R;
    if (w_refTask < 402)
        return true;//still in driving cycle
    else
        return false;//end driving cycle
}

float get_ias(){//TODO in real read from sensors
		abc_current.a= (InvClarkePark(RotorFluxAngle/*0.0*//*np*theta_r*/,tTwoPhaseDQ(ids,iqs)).a);
		return abc_current.a;
	};
float get_ibs(){//TODO in real read from sensors
		abc_current.b= (InvClarkePark(RotorFluxAngle/*0.0*//*np*theta_r*/,tTwoPhaseDQ(ids,iqs)).b);
		return abc_current.b;
	};

float Vds = 0 ;
float Vqs = 0 ;
float SincronousSpeed = 0 ;
float	s_2 = 0 ;
float Rfe = 0 ;
float fdr_ = 0 ;
float fqr_ = 0 ;
float Idm_ = 0 ;
float Iqm_ = 0 ;

float /*VehicleSimulation::*/TorqueGenMotor(float vas,float vbs,float vcs){
		 Vds=ClarkePark(RotorFluxAngle/*0.0*//*np*theta_r*/,tThreePhase(vas,vbs,vcs)).d/*alpha*/;
		 Vqs=ClarkePark(RotorFluxAngle/*0.0*//*np*theta_r*/,tThreePhase(vas,vbs,vcs)).q/*beta*/;
		 SincronousSpeed=IFOC::angle.get_wm();//sincronous speed flux on stator

    //motor_torque_g(float Vds,float Vqs,float SincronousSpeed){

//float Lls=Ls-M;
		//Vaa, vbb, vcc, generated by motor
		//TODO calc the Idm, Iqm, fqs, fds, fqr, fdr with Ids, Iqs readed values??
		//L//float Vds_g = Rs * ids /*- Rs*M*Idm/Lls*/ + (fds_ - _fds) / T - SincronousSpeed * (/*_fqs+*//*fqs_*/iqs*((Ls*Lr-M*M)/Lr))/*/2.0*//*(iqs_ant+iqs)/2.0*Lls*/;
		//L//float Vqs_g = Rs * iqs + (fqs_- _fqs) / T + SincronousSpeed * fds_;

		//L//float vaa_g, vbb_g, vcc_g;
		//L//tThreePhase v_g= InvClarkePark( RotorFluxAngle, tTwoPhaseDQ( Vds_g , Vqs_g ) );
		//L//vaa_g=v_g.a;vbb_g=v_g.b;vcc_g=v_g.c;

	//	int a0=0,b0=0,c0=0;

		//L//fTorque<<"vaa_g, vbb_g, vcc_g "<<vaa_g<<" "<<vbb_g<<" "<<vcc_g<<endl;
		//L//float vaa_med=vaa_g/*(vaa+vaa_g)/2.0*/,vbb_med=vbb_g/*(vbb+vbb_g)/2.0*/,vcc_med=vcc_g/*(vcc+vcc_g)/2.0*/;

		//L//if ((vaa_med-vbb_med)<(-VDC-0.5/*2.0*/))//estava 0.7
		//L//	{	/*a1=1;a2=1;b1=0;b2=0;*/a0=0;b0=1;
			//L//	diodes<<n*T<<"sec. diode open-a_-b med"<<endl;
		//L//		fTorque<<n*T<<"sec. diode open-a_-b med"<<endl;
				//vaa_med=(vaa+vaa_g)/2.0;vbb_med=(vbb+vbb_g)/2.0;
		//L//	}
		//L//if ((vaa_med-vcc_med)<(-VDC-0.5/*2.0*/))
			//L//{	/*a1=1;a2=1;c1=0;c2=0;*/a0=0;c0=1;
				//L//diodes<<n*T<<"sec. diode open-a_-c med"<<endl;
				//L//fTorque<<n*T<<"sec. diode open-a_-c med"<<endl;
				//vaa_med=(vaa+vaa_g)/2.0;vcc_med=(vcc+vcc_g)/2.0;
		//L//	}
		//L//if ((vbb_med-vaa_med)<(-VDC-0.5/*2.0*/))
		//L//	{	/*b1=1;b2=1;a1=0;a2=0;*/b0=0;a0=1;
			//L//	diodes<<n*T<<"sec. diode open-b_-a med"<<endl;
		//L//		fTorque<<n*T<<"sec. diode open-b_-a med"<<endl;
				//vaa_med=(vaa+vaa_g)/2.0;vbb_med=(vbb+vbb_g)/2.0;
			//L//}
		//L//if ((vbb_med-vcc_med)<(-VDC-0.5/*2.0*/))
		//L//	{	/*b1=1;b2=1;c1=0;c2=0;*/b0=0;c0=1;
			//L//	diodes<<n*T<<"sec. diode open-b_-c med"<<endl;
				//L//fTorque<<n*T<<"sec. diode open-b_-c med"<<endl;
				//vbb_med=(vbb+vbb_g)/2.0;vcc_med=(vcc+vcc_g)/2.0;
		//L//	}
	//L//	if ((vcc_med-vaa_med)<(-VDC-0.5/*2.0*/))
		//L//	{	/*c1=1;c2=1;a1=0;a2=0;*/c0=0;a0=1;
			//L//	diodes<<n*T<<"sec. diode open-c_-a med"<<endl;
				//L//fTorque<<n*T<<"sec. diode open-c_-a med"<<endl;
				//vaa_med=(vaa+vaa_g)/2.0;vcc_med=(vcc+vcc_g)/2.0;
			//L//}
		//L//if ((vcc_med-vbb_med)<(-VDC-0.5/*2.0*/))
		//L//	{	/*c1=1;c2=1;b1=0;b2=0;*/c0=0;b0=1;
			//L//	diodes<<n*T<<"sec. diode open-c_-b med"<<endl;
				//L//fTorque<<n*T<<"sec. diode open-c_-b med"<<endl;
				//vbb_med=(vbb+vbb_g)/2.0;vcc_med=(vcc+vcc_g)/2.0;
			//L//}





		/*
		if ((vaa_g-vbb_g)>0 && (vaa-vbb)>0 && ((vaa_g-vbb_g)-(vaa-vbb))>0.7*2)
			{	a1=1;a2=1;b1=0;b2=0;a0=1;b0=0;
				fTorque<<"diode open-a-b_ "<<endl;
				vaa_med=(vaa+vaa_g)/2.0;vbb_med=(vbb+vbb_g)/2.0;
			}
		if ((vaa_g-vcc_g)>0 && (vaa-vcc)>0 && ((vaa_g-vcc_g)-(vaa-vcc))>0.7*2)
			{	a1=1;a2=1;c1=0;c2=0;a0=1;c0=0;
				fTorque<<"diode open-a-c_ "<<endl;
				vaa_med=(vaa+vaa_g)/2.0;vcc_med=(vcc+vcc_g)/2.0;
			}
		if ((vbb_g-vaa_g)>0 && (vbb-vaa)>0 && ((vbb_g-vaa_g)-(vbb-vaa))>0.7*2)
			{	b1=1;b2=1;a1=0;a2=0;b0=1;a0=0;
				fTorque<<"diode open-b-a_ "<<endl;
				vaa_med=(vaa+vaa_g)/2.0;vbb_med=(vbb+vbb_g)/2.0;
			}
		if ((vbb_g-vcc_g)>0 && (vbb-vcc)>0 && ((vbb_g-vcc_g)-(vbb-vcc))>0.7*2)
			{	b1=1;b2=1;c1=0;c2=0;b0=1;c0=0;
				fTorque<<"diode open-b-c_ "<<endl;
				vbb_med=(vbb+vbb_g)/2.0;vcc_med=(vcc+vcc_g)/2.0;
			}
		if ((vcc_g-vaa_g)>0 && (vcc-vaa)>0 && ((vcc_g-vaa_g)-(vcc-vaa))>0.7*2)
			{	c1=1;c2=1;a1=0;a2=0;c0=1;a0=0;
				fTorque<<"diode open-c-a_ "<<endl;
				vaa_med=(vaa+vaa_g)/2.0;vcc_med=(vcc+vcc_g)/2.0;
			}
		if ((vcc_g-vbb_g)>0 && (vcc-vbb)>0 && ((vcc_g-vbb_g)-(vcc-vbb))>0.7*2)
			{	c1=1;c2=1;b1=0;b2=0;c0=1;b0=0;
				fTorque<<"diode open-c-b_ "<<endl;
				vbb_med=(vbb+vbb_g)/2.0;vcc_med=(vcc+vcc_g)/2.0;
			}
		*/
		//TODO :??in embedded its needed read tensions?? Power sources: battery + Load
//		(........)
		if (SincronousSpeed==0.0)SincronousSpeed = 0.000001;
		s_2=(SincronousSpeed-wr*np)/SincronousSpeed*(SincronousSpeed-wr*np)/SincronousSpeed;
		Rfe = Rm / ( s_2 + 1 ) ;
		if(ni < 20)
		printf("Rfe*1000 %f",FP_FROMFLT(Rfe*1000));
		//usado (fds_n+1-fds_n)/T=fds_n+1 +(...), e nao: (fds_n+1/T-fds_n)/T=fds_n+(...)

		fds_=1/(1/T+Rs/Lls)*(Vds+fds/T+/*np*wr*/SincronousSpeed*fqs+Rs*M/Lls*Idm);
		fqs_=1/(1/T+Rs/Lls)*(Vqs+fqs/T-/*np*wr*/SincronousSpeed*fds+Rs*M/Lls*Iqm);
		fdr_=1/(1/T+Rr/Llr)*(fdr/T+(SincronousSpeed-np*wr)*fqr+M*Rr/Llr*Idm);
		fqr_=1/(1/T+Rr/Llr)*(fqr/T-(SincronousSpeed-np*wr)*fdr+M*Rr/Llr*Iqm);
		Idm_=1/(1/T+Rfe/Lls+Rfe/Llr+Rfe/M)*(Rfe/(Lls*M)*fds+Rfe/(M*Llr)*fdr+Idm/T+(SincronousSpeed/*-np*wr*/)*Iqm);//(-Lr/Llr*Idm+ids+fdr/Llr+SincronousSpeed/*np*wr*/*M/Rfe*Iqm)/M*Rfe;
		Iqm_=1/(1/T+Rfe/Lls+Rfe/Llr+Rfe/M)*(Rfe/(Lls*M)*fqs+Rfe/(M*Llr)*fqr+Iqm/T-(SincronousSpeed/*-np*wr*/)*Idm);//(-Lr/Llr*Iqm+iqs-SincronousSpeed/*np*wr*/*M/Rfe*Idm)/M*Rfe;
//Idm = 1/(1/T+Rfe/Lls+Rfe/Llr+Rfe/M)*(Rfe/(Lls*M)*(ids * Lls + M * Idm)+Rfe/(M*Llr)*fdr+Idm/T+(SincronousSpeed/*-np*wr*/)*Iqm);

		//float _fds,_fqs;
		_fds=fds;_fqs=fqs;

		fds=fds_;
		fqs=fqs_;
		fdr=fdr_;
		fqr=fqr_;
		Idm=Idm_;
		Iqm=Iqm_;

		ids_ant=ids; iqs_ant=iqs;

		ids=(fds-M*Idm)/Lls;//fds = ids * Lls + M * Idm;
		iqs=(fqs-M*Iqm)/Lls;//fqs = iqs * Lls + M * Iqm;

	/*:2%for mecanic losses and magnetic losses*/
	if (( TorqGenMotor * wr )<0 /*&& (IDC/*VDC*//*)<0*/) sum_power_out += ABS(IDC*VDC) ; else sum_power_out += (TorqGenMotor*wr);
	if (( TorqGenMotor * wr )<0 /*&& (IDC*//*VDC*//*)<0*/) sum_power_in += ABS(TorqGenMotor*wr); else sum_power_in += (IDC*VDC);
	//sum_power_trac += t*wr;
		//L//if (n%2 == 0 /*&& n != 0*/){
			//L//fTorque<<"Vds: "<<Vds<<" Vqs: "<<Vqs<<" SincronousSpeed:"<<SincronousSpeed<<endl;

		sum_power_battery += IDC*VDC*T/3600;
		//L//fTorque<<"battery energy consumed : "<<sum_power_battery<<" wh"<<endl;
		//L//if (n*T==195)
           //L// fTorque<<"efficiency end cycle "<<sum_power_out/sum_power_in<<endl;
              Param::SetFloat(Param::motor_efficiency, (sum_power_out/sum_power_in));

		//L//fTorque<<FIXED_FLOAT(n*T)<<" sec., Torque_generated (previous): "<<t/*<<"torq_i:"<<(3/2*P/2*(fds*iqs-fqs*ids))*/<<endl<<"power (Torque_generated*rotor_velocity)(previous):"<<(t/*np*/*wr)<<"; power (Vdc*Idc)(previous):"<<(IDC*VDC)<<endl;if (IDC<0) fTorque<<"efficiency (instant. generat.)(previous) :"<<(IDC*VDC)/(t/*np*/*wr);else fTorque<<" efficiency (instant. motor)(previous):"<<(t/*np*/*wr)/(IDC*VDC);fTorque<<" machine medium efficiency: "<<sum_power_out/sum_power_in/*<<" ef: "<<sum_power_trac/sum_power_battery*/<<endl<<"Wm, same than We- sincronous speed in ang. electric: "<<SincronousSpeed<<endl<<"(SincronousSpeed-wr*np) \"slip angle:\" "<<(SincronousSpeed-wr*np)<<endl;//<<"torq_l:"<<torq_L<<endl;
		//L//};
	TorqGenMotor = /*0.98*//*<-losses mec., histerese*/(3.0/2.0*M*np/Lr/ro/Ls*(fdr*(fqs)-fqr*(fds)));//torque generated by the tension applied
//printf("torqgen %f \r\n", FP_FROMFLT( TorqGenMotor ) );
	return TorqGenMotor;
}


float J1=J;
	float T_l = 0 ;
	float n1 = 0 ;
	float n2 = 0;//??
	float Wfc = 0 ;
float Ru = 0 ;
float Xto = 0 ;
float Ffc = 0 ;
float Tfc = 0 ;
void clutch(){//
	J1=J;
	//float J2=MASSA*R*R/T_G_R/T_G_R;
	//float Te=TorqueGenMotor(va,vb,vc);
	T_l=get_torq_L();
	n1=get_w_r();
	//Torq_net=Te-T_l;
	n2=velocidade;//??
	Wfc=n2-n1;

//	unsigned int zz = (/*cosh*/(exp(float(fi*R2_*Wfc))+exp(float(-fi*R2_*Wfc)))/2);
//	unsigned int zzz = (/*cosh*/(exp(float(fi*R1_*Wfc))+exp(float(-fi*R1_*Wfc)))/2);
//	float Ru=1.0/(R2_-R1_)*(us/2.0*R2_*R2_+(ud-us)*(R2_+1.0)/(fi*Wfc)*/*log ASK*/fp_ln(zz)-(us/2.0*R1_*R1_+(ud-us)*(R1_+1.0)/(fi*Wfc)*/*log*/fp_ln(zzz)));
//	float Xto=XTO_MAX/(CLUTCH_TIME/T)*clutch_time;
//	float Ffc=F_MAX;
//	if (Xto>0.0 && Xto<=XTO_CNT)
//		{Ffc=0.0;}
//	else if(Xto>XTO_CNT && Xto<=XTO_CLS)
//			Ffc=F_MAX*(1.0-fp_sqrt(1.0-/*pow((Xto-XTO_CNT)/(XTO_CLS-XTO_CNT),2)*/(Xto-XTO_CNT)/(XTO_CLS-XTO_CNT)*(Xto-XTO_CNT)/(XTO_CLS-XTO_CNT)));
//	float Tfc=-N_P*Ru*Ffc/T_G_R;

	//unsigned int zz = (/*cosh*/(exp(float(fi*R2_*Wfc))+exp(float(-fi*R2_*Wfc)))/2);
	//unsigned int zzz = (/*cosh*/(exp(float(fi*R1_*Wfc))+exp(float(-fi*R1_*Wfc)))/2);
	//float Ru=1.0/(R2_-R1_)*(us/2.0*R2_*R2_+(ud-us)*(R2_+1.0)/(fi*Wfc)*/*log ASK*/fp_ln(zz)-(us/2.0*R1_*R1_+(ud-us)*(R1_+1.0)/(fi*Wfc)*/*log*/fp_ln(zzz)));
	
	if ( Wfc == 0.0 ) Wfc = 0.00001  ;//new clutch
	 Ru=1.0/(R2_-R1_)*(US/2.0*R2_*R2_+(UD-US)*(R2_+1.0)/(FI*Wfc)*log(cosh(FI*R2_ *Wfc))-(US/2.0*R1_ *R1_ +(UD-US)*( R1_ +1.0)/(FI*Wfc)*log(cosh(FI*R1_*Wfc))));
	Xto=XTO_MAX/(CLUTCH_TIME/T)*clutch_time;
	Ffc = F_MAX;
	if (Xto>0.0 && Xto<=XTO_CNT)
		{Ffc=0.0;}
	else if(Xto>XTO_CNT && Xto<=XTO_CLS)
			Ffc=F_MAX*(1.0-fp_sqrt(1.0-/*pow((Xto-XTO_CNT)/(XTO_CLS-XTO_CNT),2)*/(Xto-XTO_CNT)/(XTO_CLS-XTO_CNT)*(Xto-XTO_CNT)/(XTO_CLS-XTO_CNT)));
	Tfc=-N_P*Ru*Ffc/T_G_R;


	n1=n1+(Te-Tfc)/J1*T;
	n2=n2+(Tfc-T_l)/J2*T;

	velocidade=n2;
	wr=n1;
	//L//	fVel<<"Wr(rotor velocity): "<<n1<</*" a: "<<a<<*/" torque_clutch: "<<Tfc<<endl;
};
float a = 0 ;

float get_wr(float va,float vb,float vc/*float torq_g,float torq_L*/){
		a = atan(gradiente);//TODO estava comentado este e alinha a seguir --load in ifoc_2_sem_gui
		torq_L = (C_D*1/2*RO_AIR*A_F*wr/T_G_R*R*wr/T_G_R*R+C_R*MASSA*G*cos(a)+MASSA*G*sin(a))*R/T_G_R;


		Te = /*VehicleSimulation::*/TorqueGenMotor(va,vb,vc);
		if (DrivingCycle==true){
        if ( wr * np < 444/*380*/ && gear_ == 2 /*&& velocidade < velo_ant_red * 0.9 *//*|| velocidade < Wc && velocidade < velo_ant_red * 0.9*/){
			//	velo_ant_red = velocidade;
				//fVel<<" < Wn*0.66 "<<endl;
				gear_--;
				T_G_R = T_G_R_[ (gear_ - 1) ];
			}
			if ( wr * np > 975/*835*//*Wc*0.92*/ && gear_ == 1 /*&& velocidade > velo_ant_red * 1.1*/ ){
			//	velo_ant_red = velocidade;
				//fVel<<" > Wn*0.7 "<<endl;
				gear_++;
				T_G_R = T_G_R_[ (gear_ - 1) ];
			}
			if ( wr * np > 1500/*1600*//*1300*//*835*//*Wc*0.92*/ && gear_ == 2 /*&& velocidade > velo_ant_red * 1.1*/ ){
			//	velo_ant_red = velocidade;
				//fVel<<" > Wn*1.4 "<<endl;
				gear_++;
				T_G_R = T_G_R_[ (gear_ - 1) ];
			}
			if ( wr * np < 380 && gear_ == 3 /*&& velocidade < velo_ant_red * 0.9 *//*|| velocidade < Wc && velocidade < velo_ant_red * 0.9*/){
			//	velo_ant_red = velocidade;
				//fVel<<" < Wn*1.3 "<<endl;
				gear_--;
				T_G_R = T_G_R_[ (gear_ - 1) ];
			}

			if (T_G_R_ant!=T_G_R){
				T_G_R_b_clutch=T_G_R_ant;
				//wr = wr *T_G_R/T_G_R_ant;
				w_ref_ant=w_ref;
				flag_no_torque_motor = true;
//				w_ref=0;//jan 2019 ;w_ref *T_G_R/T_G_R_ant;/*end_f*1000/3600*T_G_R/R*/;

				clutch_time=CLUTCH_TIME*1/T;
				velocidade=velocidade*T_G_R/T_G_R_ant;
				T_G_R_ant=T_G_R;
				n_rtc=0;
				//FOC::angle.reset();
				}

			}


		J2=MASSA*R*R/T_G_R/T_G_R;
		if(DrivingCycle==true ){//if driving cycle:
			if (clutch_time>0){
				clutch();
				//torq_L-=torque_clutch;
				if (clutch_time==1)
				{
				flag_no_torque_motor = false;

				w_ref=w_ref_ant;}
				//_//fwref<<FIXED_FLOAT(n*T)<<"clutch_time: "<<clutch_time<<endl;

				clutch_time--;
				}
			//if (clutch_time==0){
				//torq_L-=torque_clutch;
				//clutch_time=clutch_time-3;
			//	}
			else if (velocidade>0.0 && (velocidade>wr*1.05 || velocidade<wr*0.95))
					clutch();
					else if (velocidade<0.0 && (velocidade<wr*1.05 || velocidade>wr*0.95))
					clutch();
				else{
					Torq_net=Te-torq_L;
					wr=wr+(Torq_net)*T/(J+J2/*R*R*MASSA/(T_G_R*T_G_R)*/);
					velocidade=wr;
					}
		}
		else{//if vheicle mode or by load??not sure//T_G_R=1.436*4.1;//TODONEw, test load 3rth
			if (T_G_R_ant!=T_G_R){
				//wr = wr *T_G_R/T_G_R_ant;
				w_ref_ant=w_ref;
				flag_no_torque_motor = true;//TODO

				w_ref=0;//w_ref *T_G_R/T_G_R_ant;/*end_f*1000/3600*T_G_R/R*/;
			////	clutch_time=CLUTCH_TIME*10000;
				clutch_time=CLUTCH_TIME*1/T;
				velocidade=velocidade*T_G_R/T_G_R_ant;
				T_G_R_ant=T_G_R;
				n_rtc=0;
			////	//IFOC::angle.reset();
			}
			if (clutch_time>0){
				clutch();
				//torq_L-=torque_clutch;
				clutch_time--;
				if (clutch_time==1){
					w_ref=w_ref_ant;
					flag_no_torque_motor = false;
				}
				//_//fwref<<FIXED_FLOAT(n*T)<<"clutch_time: "<<clutch_time<<endl;

				}
			//if (clutch_time==0){
				//torq_L-=torque_clutch;
				//clutch_time-=3;
			//	}
			else {
				if (T_G_R==0){
					wr=wr+(Te/*TorqueGenMotor(va,vb,vc)-torq_L*/)*T/J;
					velocidade+=torq_L/J2*T;
					}
				else if (velocidade>0.0 && (velocidade>wr*1.05 || velocidade<wr*0.95))
					clutch();
					else if (velocidade<0.0 && (velocidade<wr*1.05 || velocidade>wr*0.95))
					clutch();
					else{
						Torq_net=Te/*TorqueGenMotor(va,vb,vc)*/-torq_L;
						wr=wr+(Torq_net)*T/(J+J2/*R*R*MASSA/(T_G_R*T_G_R)*/);
						velocidade=wr;
					}
			}
			}
			//L//if (n%2 == 0 /*&& n != 0*/){
			//L//	fTorque<<" w_ref "<<w_ref<<" wr "<<wr<<endl;
			//L//}
		return wr;
};

#endif // VehicleSimulation



//VehicleSimulation::VehicleSimulation()
//{
    //ctor
//}

//VehicleSimulation::~VehicleSimulation()
//{
    //dtor
//}
